services:
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fuel_db
      MYSQL_USER: fuel_user
      MYSQL_PASSWORD: secret
    volumes:
      - ./db_data:/var/lib/mysql
      # - db_data:/var/lib/mysql

    ports:
      - "33066:3306"
  redis-master:
    image: redis:7
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass secret123
  supervisor:
    build:
      context: .
      dockerfile: Docker/supervisor/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - php
      - redis-master
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
volumes:
  db_data:
